steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--build-arg',
    'ENV=${_ENV}',
    '-t',
    'gcr.io/${PROJECT_ID}/quickstart-image:${COMMIT_SHA}',
    '.'
    ]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/${PROJECT_ID}/quickstart-image:${COMMIT_SHA}"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment/builder-test
  - builder-test=gcr.io/${PROJECT_ID}/quickstart-image:${COMMIT_SHA}
  env:
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}
