steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--build-arg',
    'ENV=${_ENV}',
    '-t',
    'gcr.io/${PROJECT_ID}/${REPO_NAME}/${BRANCH_NAME}:${SHORT_SHA}',
    '.'
    ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/${REPO_NAME}/${BRANCH_NAME}:${SHORT_SHA}']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment/${REPO_NAME}
  - ${REPO_NAME}=gcr.io/${PROJECT_ID}/${REPO_NAME}/${BRANCH_NAME}:${SHORT_SHA}
  env:
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
